// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

type Empires struct {
	ID       int64
	GameID   int64
	PlayerID int64
}

type Games struct {
	ID          int64
	Code        string
	Name        string
	DisplayName string
	CurrentTurn int64
}

type NaturalResources struct {
	ID        int64
	OrbitID   int64
	DepositNo int64
	Kind      string
	Quantity  int64
	YieldPct  int64
}

type Orbits struct {
	ID           int64
	StarID       int64
	Orbit        int64
	Kind         string
	Habitability int64
}

type Players struct {
	ID int64
}

type Stars struct {
	ID       int64
	SystemID int64
	Sequence int64
}

type Systems struct {
	ID     int64
	GameID int64
	X      int64
	Y      int64
	Z      int64
}
